stages:
  - build
  - shadowjar
  - release

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'

default:
  tags:
    - 'mais'
  image: gradle:jdk17

build:
  stage: build
  before_script:
    - echo "Building..."
  script:
    - gradle clean build
  artifacts:
    paths:
      - build/
    expire_in: 1 hour

shadowjar:
  stage: shadowjar
  before_script:
    - echo "Creating shadowJar..."
  script:
    - gradle shadowJar
  artifacts:
    paths:
      - build/libs/SimpleTreeCaptiator-*.jar
    expire_in: 1 hour

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: shadowjar
      artifacts: true
  script:
    - ls -la build/libs/ || echo "No files found in build/libs/"
    - VERSION=$(ls build/libs/SimpleTreeCapiator-*-all.jar | sed -n 's/.*SimpleTreeCapiator-\([0-9]\+\.[0-9]\+\.[0-9]\+\)-all\.jar/\1/p')
    - mv build/libs/SimpleTreeCapiator-${VERSION}-all.jar build/libs/SimpleTreeCapiator-${VERSION}.jar
    - echo "Creating release for SimpleTreeCapiator ${VERSION}"
  release:
    name: 'SimpleTreeCapiator ${VERSION}'
    description: '$CI_COMMIT_MESSAGE'
    tag_name: '${VERSION}'
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: 'SimpleTreeCapiator-${VERSION}.jar'
          url: '$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/SimpleTreeCapiator/${VERSION}/SimpleTreeCapiator-${VERSION}.jar'
          filepath: '/SimpleTreeCapiator/${VERSION}/SimpleTreeCapiator-${VERSION}.jar'
          link_type: 'package'
