stages:
  - build
  - shadowjar
  - release

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'

default:
  tags:
    - 'mais'
  image: gradle:jdk17

build:
  stage: build
  before_script:
    - echo "Building..."
  script:
    - gradle clean build
  artifacts:
    paths:
      - build/
    expire_in: 1 hour

shadowjar:
  stage: shadowjar
  before_script:
    - echo "Creating shadowJar..."
  script:
    - gradle shadowJar
  artifacts:
    paths:
      - build/libs/*-all.jar
    expire_in: 1 hour

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: shadowjar
      artifacts: true
  script:
    - JAR_FILE=$(ls build/libs/*-all.jar)
    - PROJECT_NAME=$(basename "$JAR_FILE" | sed -E 's/-[0-9]+\.[0-9]+\.[0-9]+-all\.jar$//')
    - VERSION=$(basename "$JAR_FILE" | sed -E 's/.*-([0-9]+\.[0-9]+\.[0-9]+)-all\.jar$/\1/')
    - mv "$JAR_FILE" "build/libs/${PROJECT_NAME}-${VERSION}.jar"
    - echo "Creating release for ${PROJECT_NAME} ${VERSION}"
  release:
    name: '${PROJECT_NAME} ${VERSION}'
    description: '$CI_COMMIT_MESSAGE'
    tag_name: '${VERSION}'
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: '${PROJECT_NAME}-${VERSION}.jar'
          url: '$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/${PROJECT_NAME}/${VERSION}/${PROJECT_NAME}-${VERSION}.jar'
          filepath: '/${PROJECT_NAME}/${VERSION}/${PROJECT_NAME}-${VERSION}.jar'
          link_type: 'package'
